# (C) Copyright 2026, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

import json
from pathlib import Path
from typing import Any, Optional, Union
import requests
from typing import List

import pytest
from astarte.device import Interface
from dotenv import dotenv_values
from twister_harness import DeviceAdapter, Shell

class MissingConfigError(Exception):
    def __init__(self, key: str) -> None:
        super().__init__(f"Missing required configuration value for key: {key}")


class Configuration:
    dut: DeviceAdapter
    shell: Shell
    realm: str
    device_id: str
    appengine_url: str
    appengine_token: str
    appengine_cert: Path
    http_server_data_dir: Path
    http_server_cert: Path
    http_server_key: Path
    http_server_port: int
    log_only: bool
    interfaces: list[Interface]

    def __init__(
        self, config_file_path: Union[str, Path], dut: DeviceAdapter, shell: Shell
    ) -> None:
        self.dut = dut
        self.shell = shell

        prj_config: dict[str, Optional[str]] = dotenv_values(config_file_path)

        self.realm = self._get_config_value(prj_config, "CONFIG_ASTARTE_DEVICE_SDK_REALM_NAME")
        self.device_id = self._get_config_value(prj_config, "CONFIG_E2E_ASTARTE_DEVICE_ID")
        self.appengine_url = self._get_config_value(prj_config, "CONFIG_E2E_APPENGINE_URL")
        self.appengine_token = self._get_config_value(prj_config, "CONFIG_E2E_APPENGINE_TOKEN")

        end_to_end_root_path = Path(__file__).resolve().parents[1]

        astarte_cert_path: str = self._get_config_value(prj_config, "CONFIG_E2E_ASTARTE_TLS_CERTIFICATE_PATH")
        self.appengine_cert = end_to_end_root_path / astarte_cert_path

        server_data_path: str = self._get_config_value(prj_config, "CONFIG_E2E_HTTP_SERVER_DATA_DIR")
        self.http_server_data_dir = end_to_end_root_path / server_data_path
        server_cert_path: str = self._get_config_value(prj_config, "CONFIG_E2E_HTTP_SERVER_CERT_DIR")
        self.http_server_cert = end_to_end_root_path / server_cert_path / "192.0.2.2.pem"
        self.http_server_key = end_to_end_root_path / server_cert_path / "192.0.2.2.key"
        self.http_server_port = int(self._get_config_value(prj_config, "CONFIG_E2E_HTTP_SERVER_PORT"))

        try:
            self.log_only = self._get_config_value(prj_config, "CONFIG_E2E_LOG_ONLY").lower() == "y"
        except MissingConfigError:
            self.log_only = False

        self.interfaces = []
        for interface_json in get_edgehog_json_interfaces():
            self.interfaces.append(Interface(interface_json))


    @staticmethod
    def _get_config_value(config: dict[str, Optional[str]], key: str) -> str:
        value: Optional[str] = config.get(key)

        if value is None or not value:
            raise MissingConfigError(key)

        # Strip literal quotes generated by Zephyr Kconfig
        return value.strip('"')

# NOTE: There might be some restrictions from the GitHub API to get this data at a rapid rate.
# See: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api
def get_edgehog_json_interfaces() -> List[dict]:
    """
    Fetches the unparsed content of all JSON files in the root of the
    edgehog-device-manager/edgehog-astarte-interfaces repository.
    """
    api_url = "https://api.github.com/repos/edgehog-device-manager/edgehog-astarte-interfaces/contents/"
    json_file_contents = []

    # Get the directory listing of the repo root
    response = requests.get(api_url)
    response.raise_for_status()

    for item in response.json():
        # Look only for files that end with .json
        if item.get("type") == "file" and item.get("name", "").endswith(".json"):
            download_url = item["download_url"]

            # Fetch the raw text content of the file
            file_response = requests.get(download_url)
            file_response.raise_for_status()

            json_file_contents.append(file_response.text)

    return [json.loads(json_file_content) for json_file_content in json_file_contents]

@pytest.fixture(scope="session")
def end_to_end_configuration(dut: DeviceAdapter, shell: Shell) -> Configuration:
    cfg_file: Path = Path(dut.device_config.build_dir) / "zephyr" / ".config"
    return Configuration(cfg_file, dut, shell)
