/*
 * (C) Copyright 2024, SECO Mind Srl
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "nvs.h"

#include <zephyr/drivers/flash.h>
#include <zephyr/fs/nvs.h>
#include <zephyr/storage/flash_map.h>

#include "log.h"
EDGEHOG_LOG_MODULE_REGISTER(edgehog_nvs, CONFIG_EDGEHOG_DEVICE_NVS_LOG_LEVEL);

#ifdef CONFIG_EDGEHOG_DEVICE_USE_EDGEHOG_PARTITION
#define NVS_PARTITION edgehog_partition
#else
#define NVS_PARTITION storage_partition
#endif

/* FIXED_PARTITION_ID() values used below are auto-generated by DT */
#define NVS_PARTITION_DEVICE FIXED_PARTITION_DEVICE(NVS_PARTITION)
#define NVS_PARTITION_OFFSET FIXED_PARTITION_OFFSET(NVS_PARTITION)

edgehog_result_t edgehog_nvs_open(struct nvs_fs *out_fs)
{
    struct flash_pages_info info;

    /*  define the nvs file system by settings with:
     *	sector_size equal to the pagesize,
     *	3 sectors
     *	starting at NVS_PARTITION_OFFSET
     */
    out_fs->flash_device = NVS_PARTITION_DEVICE;
    if (!device_is_ready(out_fs->flash_device)) {
        EDGEHOG_LOG_ERR("Flash device %s is not ready", out_fs->flash_device->name);
        return EDGEHOG_RESULT_DEVICE_NOT_READY;
    }
    out_fs->offset = NVS_PARTITION_OFFSET;
    int result = flash_get_page_info_by_offs(out_fs->flash_device, out_fs->offset, &info);
    if (result != 0) {
        EDGEHOG_LOG_ERR("Unable to get page info err:%d", result);
        return EDGEHOG_RESULT_NVS_ERROR;
    }
    out_fs->sector_size = info.size;
    out_fs->sector_count = 3U;

    result = nvs_mount(out_fs);
    if (result != 0) {
        EDGEHOG_LOG_ERR("Unable to mount NVS, Flash Init failed err:%d", result);
        return EDGEHOG_RESULT_NVS_ERROR;
    }

    return EDGEHOG_RESULT_OK;
}
