# (C) Copyright 2026, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

# Provide enough stack space for MbedTLS crypto and HTTPS handshakes
CONFIG_E2E_DEVICE_THREAD_STACK_SIZE=16384
CONFIG_SHELL_STACK_SIZE=16384

# Enable the simulated flash driver for NVS
CONFIG_FLASH_SIMULATOR=y

# Print logs immediately to catch fatal errors before exit
CONFIG_LOG_MODE_IMMEDIATE=y

# Enable PCIe bus to support the e1000 driver
CONFIG_PCIE=y

# QEMU Ethernet settings (emulated e1000)
CONFIG_NET_L2_ETHERNET=y
CONFIG_ETH_E1000=y

# Enable the QEMU network backend
CONFIG_NET_QEMU_ETHERNET=y

# Network application options and configuration
CONFIG_NET_DHCPV4=n
CONFIG_NET_DHCPV6=n
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV6=y
CONFIG_NET_CONFIG_MY_IPV6_ADDR="2001:db8::1"
CONFIG_NET_CONFIG_PEER_IPV6_ADDR="2001:db8::2"
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.2"
CONFIG_NET_CONFIG_MY_IPV4_GW="192.0.2.2"
