/*
 * (C) Copyright 2024, SECO Mind Srl
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef WIFI_SCAN_H
#define WIFI_SCAN_H

// #ifdef CONFIG_WIFI

// /**
//  * @file wifi_scan.h
//  */

// /**
//  * @defgroup wifi WiFi scan
//  * @brief API for a WiFi scan.
//  * @ingroup edgehog_device
//  * @{
//  */

// #include "edgehog_device/device.h"
// #include "edgehog_device/result.h"

// #include <zephyr/net/wifi_mgmt.h>

// /**
//  * @brief The WiFi events required for the scan.
//  */
// #define EDGEHOG_WIFI_SCAN_EVENTS_SET (NET_EVENT_WIFI_SCAN_DONE | NET_EVENT_WIFI_CONNECT_RESULT)

// #ifdef __cplusplus
// extern "C" {
// #endif

// /**
//  * @brief Perfom a WiFi scan request.
//  *
//  * @return EDGEHOG_RESULT_OK if successful, otherwise an error code.
//  */
// edgehog_result_t edgehog_wifi_scan_start(void);

// /**
//  * @brief Handle for WiFi scan event.
//  *
//  * @details This function handles an WiFi scan event generated by the network management.
//  *
//  * @param mgmt_event The exact request value the handler is being called through.
//  * @param iface A valid pointer on struct net_if if the request is meant to be tight to a network
//  * interface. NULL otherwise.
//  * @param data A valid pointer on a data understood by the handler. NULL otherwise.
//  * @param data_len Length in byte of the memory pointed by data.
//  * @param user_data Data provided by the user to the handler.
//  */
// void edgehog_wifi_scan_event_handler(
//     uint32_t mgmt_event, struct net_if *iface, void *data, size_t data_len, void *user_data);

// #ifdef __cplusplus
// }
// #endif

// /**
//  * @}
//  */

// #endif

#endif // WIFI_SCAN_H
