#
# This file is part of Edgehog.
#
# Copyright 2024 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

name: Documentation Build

on:
  push:
    tags:
    - v*
  pull_request:
    paths:
    - 'README.md'
    - 'doc/**'
    - 'include/**'
    - '.github/workflows/doc-build.yml'
    - 'scripts/docs.py'
    - 'scripts/west-commands.py'
    - 'scripts/requirements.txt'

env:
  # The latest CMake available directly with apt is 3.18, but we need >=3.20,
  # so we fetch that through pip.
  CMAKE_VERSION: 3.22.1
  DOXYGEN_VERSION: 1.9.6

jobs:
  doc-build-html:
    name: "Documentation Build (HTML)"
    runs-on: ubuntu-latest
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.6
    timeout-minutes: 45
    concurrency:
      group: doc-build-html-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: edgehog-zephyr-device

    - name: Install ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build graphviz

    - name: Install doxygen
      working-directory: edgehog-zephyr-device
      shell: bash
      run: |
        wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
        tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
        echo "${PWD}/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH

    - name: Install python packages
      run: |
        pip3 install cmake==${CMAKE_VERSION}

    - name: West setup
      working-directory: edgehog-zephyr-device
      run: |
        west init -l .

    - name: Build documentation
      working-directory: edgehog-zephyr-device
      shell: bash
      run: |
        if [[ "$GITHUB_REF" =~ "refs/tags/v" ]]; then
          DOC_TAG="release"
        else
          DOC_TAG="development"
        fi

        DOC_TAG=${DOC_TAG} EDGEHOG_DEVICE_BASE="$PWD" make -C doc doxygen

    - name: Upload HTML documentation
      uses: actions/upload-artifact@v4
      with:
        name: docs_html
        path: edgehog-zephyr/doc/_build/doxygen/html-device

    - name: Build extended documentation
      working-directory: edgehog-zephyr-device
      shell: bash
      run: |
        if [[ "$GITHUB_REF" =~ "refs/tags/v" ]]; then
          DOC_TAG="release"
        else
          DOC_TAG="development"
        fi

        DOC_TAG=${DOC_TAG} EDGEHOG_DEVICE_BASE="$PWD" EDGEHOG_DEVICE_EXTENDED_DOCS="yes" make -C doc doxygen
